services:
  backend:
    hostname: backend
    build:
      context: unreal-analytics-server
    stop_signal: SIGINT
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=9953
    volumes:
      # - ./unreal-analytics-server/config:/app/config
      # - ./unreal-analytics-server/src:/app/src
      # - ./unreal-analytics-server/www:/app/www
      # - ./unreal-analytics-server/target:/app/target
      - ./unreal-analytics-server:/app
    ports:
      - 9953:9953
    depends_on:
      - mongo
    restart: always

  todolist:
    hostname: todolist
    build:
      context: unreal-todo-list
    stop_signal: SIGINT
    volumes:
      - ./unreal-todo-list:/app
    ports:
      - 9092:9092
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
